// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: Peer.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBServerSpecificInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address           string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	LastHandshakeTime string `protobuf:"bytes,2,opt,name=LastHandshakeTime,proto3" json:"LastHandshakeTime,omitempty"`
	Endpoint          string `protobuf:"bytes,3,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	CurrentTX         int64  `protobuf:"varint,4,opt,name=CurrentTX,proto3" json:"CurrentTX,omitempty"`
	CurrentRX         int64  `protobuf:"varint,5,opt,name=CurrentRX,proto3" json:"CurrentRX,omitempty"`
}

func (x *PBServerSpecificInfo) Reset() {
	*x = PBServerSpecificInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Peer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBServerSpecificInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBServerSpecificInfo) ProtoMessage() {}

func (x *PBServerSpecificInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Peer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBServerSpecificInfo.ProtoReflect.Descriptor instead.
func (*PBServerSpecificInfo) Descriptor() ([]byte, []int) {
	return file_Peer_proto_rawDescGZIP(), []int{0}
}

func (x *PBServerSpecificInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PBServerSpecificInfo) GetLastHandshakeTime() string {
	if x != nil {
		return x.LastHandshakeTime
	}
	return ""
}

func (x *PBServerSpecificInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PBServerSpecificInfo) GetCurrentTX() int64 {
	if x != nil {
		return x.CurrentTX
	}
	return 0
}

func (x *PBServerSpecificInfo) GetCurrentRX() int64 {
	if x != nil {
		return x.CurrentRX
	}
	return 0
}

type PBPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                 string                  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name               string                  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	AllowedIPs         string                  `protobuf:"bytes,3,opt,name=AllowedIPs,proto3" json:"AllowedIPs,omitempty"`
	Disabled           bool                    `protobuf:"varint,4,opt,name=Disabled,proto3" json:"Disabled,omitempty"`
	AllowedUsage       int64                   `protobuf:"varint,5,opt,name=AllowedUsage,proto3" json:"AllowedUsage,omitempty"`
	ExpiresAt          int64                   `protobuf:"varint,6,opt,name=ExpiresAt,proto3" json:"ExpiresAt,omitempty"`
	TotalTX            int64                   `protobuf:"varint,7,opt,name=TotalTX,proto3" json:"TotalTX,omitempty"`
	TotalRX            int64                   `protobuf:"varint,8,opt,name=TotalRX,proto3" json:"TotalRX,omitempty"`
	ServerSpecificInfo []*PBServerSpecificInfo `protobuf:"bytes,9,rep,name=ServerSpecificInfo,proto3" json:"ServerSpecificInfo,omitempty"`
}

func (x *PBPeer) Reset() {
	*x = PBPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Peer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBPeer) ProtoMessage() {}

func (x *PBPeer) ProtoReflect() protoreflect.Message {
	mi := &file_Peer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBPeer.ProtoReflect.Descriptor instead.
func (*PBPeer) Descriptor() ([]byte, []int) {
	return file_Peer_proto_rawDescGZIP(), []int{1}
}

func (x *PBPeer) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *PBPeer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PBPeer) GetAllowedIPs() string {
	if x != nil {
		return x.AllowedIPs
	}
	return ""
}

func (x *PBPeer) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *PBPeer) GetAllowedUsage() int64 {
	if x != nil {
		return x.AllowedUsage
	}
	return 0
}

func (x *PBPeer) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *PBPeer) GetTotalTX() int64 {
	if x != nil {
		return x.TotalTX
	}
	return 0
}

func (x *PBPeer) GetTotalRX() int64 {
	if x != nil {
		return x.TotalRX
	}
	return 0
}

func (x *PBPeer) GetServerSpecificInfo() []*PBServerSpecificInfo {
	if x != nil {
		return x.ServerSpecificInfo
	}
	return nil
}

type PBPeers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peers []*PBPeer `protobuf:"bytes,1,rep,name=Peers,proto3" json:"Peers,omitempty"`
	Role  string    `protobuf:"bytes,2,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *PBPeers) Reset() {
	*x = PBPeers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Peer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBPeers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBPeers) ProtoMessage() {}

func (x *PBPeers) ProtoReflect() protoreflect.Message {
	mi := &file_Peer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBPeers.ProtoReflect.Descriptor instead.
func (*PBPeers) Descriptor() ([]byte, []int) {
	return file_Peer_proto_rawDescGZIP(), []int{2}
}

func (x *PBPeers) GetPeers() []*PBPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PBPeers) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_Peer_proto protoreflect.FileDescriptor

var file_Peer_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x50, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61,
	0x69, 0x6e, 0x22, 0xb6, 0x01, 0x0a, 0x14, 0x50, 0x42, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x4c, 0x61, 0x73, 0x74, 0x48, 0x61, 0x6e,
	0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x4c, 0x61, 0x73, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x58, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x58, 0x12, 0x1c, 0x0a,
	0x09, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x58, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x58, 0x22, 0xaa, 0x02, 0x0a, 0x06,
	0x50, 0x42, 0x50, 0x65, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x50, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x50, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x64, 0x55, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x41, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x54, 0x58, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x54, 0x58, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x58, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x58, 0x12, 0x4a, 0x0a, 0x12,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x50, 0x42, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x41, 0x0a, 0x07, 0x50, 0x42, 0x50, 0x65,
	0x65, 0x72, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x50, 0x65, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x42, 0x50, 0x65, 0x65, 0x72,
	0x52, 0x05, 0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Peer_proto_rawDescOnce sync.Once
	file_Peer_proto_rawDescData = file_Peer_proto_rawDesc
)

func file_Peer_proto_rawDescGZIP() []byte {
	file_Peer_proto_rawDescOnce.Do(func() {
		file_Peer_proto_rawDescData = protoimpl.X.CompressGZIP(file_Peer_proto_rawDescData)
	})
	return file_Peer_proto_rawDescData
}

var file_Peer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Peer_proto_goTypes = []any{
	(*PBServerSpecificInfo)(nil), // 0: main.PBServerSpecificInfo
	(*PBPeer)(nil),               // 1: main.PBPeer
	(*PBPeers)(nil),              // 2: main.PBPeers
}
var file_Peer_proto_depIdxs = []int32{
	0, // 0: main.PBPeer.ServerSpecificInfo:type_name -> main.PBServerSpecificInfo
	1, // 1: main.PBPeers.Peers:type_name -> main.PBPeer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Peer_proto_init() }
func file_Peer_proto_init() {
	if File_Peer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Peer_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PBServerSpecificInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Peer_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PBPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Peer_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PBPeers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Peer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Peer_proto_goTypes,
		DependencyIndexes: file_Peer_proto_depIdxs,
		MessageInfos:      file_Peer_proto_msgTypes,
	}.Build()
	File_Peer_proto = out.File
	file_Peer_proto_rawDesc = nil
	file_Peer_proto_goTypes = nil
	file_Peer_proto_depIdxs = nil
}
